import Link from "next/link";
import { Sparkles } from "lucide-react";

export const metadata = {
  title: "Terms of Service — Personal Dashboard",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950">
      <header className="border-b border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-900">
        <div className="mx-auto flex max-w-3xl items-center gap-3 px-6 py-4">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-600">
              <Sparkles className="h-4 w-4 text-white" />
            </div>
            <span className="font-bold text-gray-900 dark:text-gray-100">Personal Dashboard</span>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-12">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-100">Terms of Service</h1>
        <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">Last updated: April 17, 2026</p>

        <div className="mt-10 space-y-8 text-sm leading-relaxed text-gray-700 dark:text-gray-300">
          <section>
            <h2 className="mb-3 text-lg font-semibold text-gray-900 dark:text-gray-100">1. Acceptance</h2>
            <p>
              By creating an account or using Personal Dashboard, you agree to these terms. If you
              do not agree, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-gray-900 dark:text-gray-100">2. The service</h2>
            <p>
              Personal Dashboard is an AI content generation tool. You can generate, edit, and save
              content using AI models accessed via OpenRouter. We provide the platform; the AI
              outputs are generated by third-party models.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-gray-900 dark:text-gray-100">3. Your account</h2>
            <ul className="ml-4 list-disc space-y-1.5">
              <li>You are responsible for maintaining the security of your Google account.</li>
              <li>You must be at least 13 years old to use this service.</li>
              <li>
                You may not use the service for any unlawful purpose or in violation of any
                regulations.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-gray-900 dark:text-gray-100">4. Credits and payments</h2>
            <ul className="ml-4 list-disc space-y-1.5">
              <li>Credits are purchased via Razorpay and are non-refundable.</li>
              <li>Credits do not expire.</li>
              <li>
                We reserve the right to change credit pricing with 14 days&apos; notice to existing
                users.
              </li>
              <li>
                If a payment fails or is disputed, we may suspend your account pending resolution.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-gray-900 dark:text-gray-100">5. Acceptable use</h2>
            <p>You may not use Personal Dashboard to:</p>
            <ul className="ml-4 mt-2 list-disc space-y-1.5">
              <li>Generate content that is illegal, harassing, defamatory, or hateful.</li>
              <li>Violate the intellectual property rights of others.</li>
              <li>Attempt to circumvent rate limits, authentication, or other security measures.</li>
              <li>Resell or redistribute access to the service without permission.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-gray-900 dark:text-gray-100">6. Content ownership</h2>
            <p>
              You own the content you create and save. By using the service, you grant us a limited
              license to store and process your content solely to provide the service. We do not
              claim ownership of your generated content.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-gray-900 dark:text-gray-100">7. Disclaimer of warranties</h2>
            <p>
              The service is provided &ldquo;as is&rdquo; without warranties of any kind. AI-generated content
              may be inaccurate, incomplete, or unsuitable. Always review content before publishing
              or relying on it.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-gray-900 dark:text-gray-100">8. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, we are not liable for any indirect, incidental,
              or consequential damages arising from your use of the service, including lost credits
              due to service interruptions.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-gray-900 dark:text-gray-100">9. Termination</h2>
            <p>
              We may suspend or terminate accounts that violate these terms. You may close your
              account at any time by contacting us.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-gray-900 dark:text-gray-100">10. Changes to terms</h2>
            <p>
              We may update these terms. Continued use after changes constitutes acceptance. We will
              notify users of material changes via the app or email.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-gray-900 dark:text-gray-100">11. Contact</h2>
            <p>
              Questions?{" "}
              <a
                href="mailto:developerlife69@gmail.com"
                className="text-indigo-600 underline dark:text-indigo-400"
              >
                developerlife69@gmail.com
              </a>
            </p>
          </section>
        </div>

        <div className="mt-12 border-t border-gray-200 pt-6 dark:border-gray-800">
          <Link
            href="/"
            className="text-sm text-indigo-600 hover:underline dark:text-indigo-400"
          >
            ← Back to home
          </Link>
        </div>
      </main>
    </div>
  );
}
